pub mod gc;
pub mod slot_to_param;
pub mod sccp;
pub mod flow_simplify;
pub mod inline;
pub mod dce;
// pub mod phi_combine;
// pub mod phi_pushing;
// pub mod mem_forwarding;
pub mod block_threading;
// pub mod instr_simplify;